### ISSUE TITLE
LabelPlus_Ps_Script_ZH.jsx不兼容Photoshop CC？

### ISSUE THREAD

**Issue by thelastfantasy** [noodlefighter/LabelPlus#48]
Photoshop弹出8800错误
![](http://pic.ffsky.net/images/2016/03/31/39df60e892c57bf3de4ddcc6f2baef01.png)

**Comment by noodlefighter** [comment]
请检查颜色模式是不是 “索引”
索引模式无法编辑编辑
尝试用动作批处理成RGB色彩模式

**Comment by thelastfantasy** [comment]
转成jpg后能用了
