### ISSUE TITLE
ps脚本 - 图源后缀 - Mac下兼容性问题

### ISSUE THREAD

**Issue by yu-liang-dev** [noodlefighter/LabelPlus#49]
脚本内后缀显示正确，日志sourceFileType显示为.psd
需要勾选指定图源后缀名为jpg之类才能使用
![qq 20160518233353](https://cloud.githubusercontent.com/assets/9611408/15364994/262e4362-1d51-11e6-831e-592b6566c122.png)
![qq 20160518233419](https://cloud.githubusercontent.com/assets/9611408/15364995/26325e20-1d51-11e6-9cef-5190bc804e37.jpg)

**Comment by jincheng95** [comment]
能否麻烦你检查一下图源路径是否正确？使用萌翻的话，一般要把图源文件夹设置成`/SQTYV72QUAL4QWDEVABQ/源图`。我看到你的log中`source`值还是root文件夹。
