### ISSUE TITLE
导入到PS时会卡住

### ISSUE THREAD

**Issue by Omgix** [noodlefighter/LabelPlus#67]
PS的版本为CC2017，设定好图源后缀名为.psd，图源位置也没错，可点击导入之后就会跳出文件管理器让我打开第一张图。打开后，又会出现“命令‘播放’当前不可用”的提示，但之后会跳出新建组的窗口，如果点击“确定”，那么接下来就会卡住，关也关不掉。
有的时候可以通过反复按“无视图片文件名”右边的preview和指定后缀名解决卡住的问题，似乎选择“处理无标号文档”和“替换文本”也能解决问题。但是，不一定能解决，就算解决了，打开每张图片的时候（以及完成一张图片的导入的时候）还是会跳出“命令‘播放’当前不可用”的提示！

PS:新发现，似乎打开多个文件管理器会触发此问题。
![20170612210206](https://user-images.githubusercontent.com/29375675/27035644-ac87b0b0-4fb4-11e7-93b4-3ff9f7470a27.png)
![20170612210250](https://user-images.githubusercontent.com/29375675/27035648-b0b04cec-4fb4-11e7-86b2-3e88b935e6c1.png)
![20170612210304](https://user-images.githubusercontent.com/29375675/27035657-b66150be-4fb4-11e7-9bd7-c8271664b5c9.png)
![20170612210315](https://user-images.githubusercontent.com/29375675/27035662-b9b3ed9e-4fb4-11e7-8a55-0d695127cc76.png)

**Comment by noodlefighter** [comment]
已经收到较多CC2017中这个问题的报告... 尝试解决中

**Comment by noodlefighter** [comment]
bug已经修复
项目目录已经转移到 https://github.com/LabelPlus/PS-Script
你可以去下载最新的release
